### ISSUE TITLE
首页有部分广告去不掉

### ISSUE THREAD

**Issue by ckn4** [ohyeah521/NoAds-For-YouTube#10]
作者你好，用了你的模块后可以方便的后台播放，谢谢你的工作。
但是刚刚打开软件时首页上方有一个广告去不掉，往下滑动一段时间也偶尔会出现类似形式的广告。
<img src="https://s1.ax1x.com/2020/05/08/Yusl3n.png" alt="Yusl3n.png" border="0" />
我的手机系统是android9，ytb版本是15.17.38，使用edxp(Y版)实现xposed功能。
不知道是不是我的个例。

**Comment by ohyeah521** [comment]
这一部分没有做处理，由于它不会影响观影体验，所以没有单独的去弄它，偷个懒^_^

**Comment by ckn4** [comment]
😂原来是这样，我还以为是我这里出了问题。
