### ISSUE TITLE
Ads showing during video playback on 14.32.51

### ISSUE THREAD

**Issue by DanGLES3** [ohyeah521/NoAds-For-YouTube#11]
Recently after I updated YouTube to 14.32.51 I'm sometimes getting ads for apps like YouTube Music,Netflix and etc.. in the beginning and end of a video  (the frequency of when ads appear or not seems to be completely random)

**Comment by ohyeah521** [comment]
@DanGLES3 Because the new version of YouTube rewrites the ad code, so the original auto-adaptation function is not working, I have just adapted the new version, please update the plug-in

**Comment by DanGLES3** [comment]
Thank you very much 😁
