### ISSUE TITLE
哥们。有意开源吗？

### ISSUE THREAD

**Issue by github-gsjb** [ohyeah521/NoAds-For-YouTube#11]
想查看广告的hook代码

**Comment by ohyeah521** [comment]
暂时不开源

**Comment by github-gsjb** [comment]
> 暂时不开源

刚好用到了。现在已经获取到pb数据。

**Comment by ohyeah521** [comment]
> > 暂时不开源
> 
> 刚好用到了。现在已经获取到pb数据。

pb数据是啥？

**Comment by github-gsjb** [comment]
> > > 暂时不开源
> > 
> > 
> > 刚好用到了。现在已经获取到pb数据。
> 
> pb数据是啥？

protocol-buffers 哈哈哈

**Comment by ohyeah521** [comment]
> > > > 暂时不开源
> > > 
> > > 
> > > 刚好用到了。现在已经获取到pb数据。
> > 
> > 
> > pb数据是啥？
> 
> protocol-buffers 哈哈哈

搜嘎
