### ISSUE TITLE
The plug-in fails

### ISSUE THREAD

**Issue by kittyzero520** [ohyeah521/NoAds-For-YouTube#12]
14.32.15 cannot block ads

**Comment by DanGLES3** [comment]
Same thing on 14.32.51, ads started showing up during video playback

**Comment by ohyeah521** [comment]
@kittyzero520 @DanGLES3  Because the new version of YouTube rewrites the ad code, so the original auto-adaptation function is not working, I have just adapted the new version, please update the plug-in

**Comment by underdoq** [comment]
I would like to thank you for this plugin, it is the best compared to YT Vanced, this just change two main problems, while Vanced is a whole new app. Its like premium is enabled, and that's great, thanks.

**Comment by ohyeah521** [comment]
@underdoq I'm glad you like this app, but also thank you for your approval, I will take more time to adapt the new version of YouTube updates in time

**Comment by kittyzero520** [comment]
I like this application very much. Thank you for your timely follow-up. Thank you very much!

**Comment by ohyeah521** [comment]
@kittyzero520 You are welcome
