### ISSUE TITLE
太极阳去广告不生效，edxposed上可以生效

### ISSUE THREAD

**Issue by OoHHHHHHH** [ohyeah521/NoAds-For-YouTube#13]
太极阳去广告不生效，edxposed上可以生效。
请问实现在太极上去广告需要加入除了YouTube以外的应用嘛？

**Comment by ohyeah521** [comment]
太极比较垃圾，提交后他们还要审核，不知道什么原因还把我账号给ban了，所以我不再适配太极。建议你使用edxposed。

**Comment by OoHHHHHHH** [comment]
> 太极比较垃圾，提交后他们还要审核，不知道什么原因还把我账号给ban了，所以我不再适配太极。建议你使用edxposed。

感谢回复，这就卸掉太极，去换edxposed！
