### ISSUE TITLE
Support  YouTube 15.33.34

### ISSUE THREAD

**Issue by NULL0B** [ohyeah521/NoAds-For-YouTube#14]
Hello the module is not  working with the current YouTube version 15.33.34 and future releases. Could you update it?, thanks

**Comment by ohyeah521** [comment]
i will update it latter,please wait.

**Comment by ajmz** [comment]
以前版本的YouTube，从后台激活时，有时会造成手机卡死，新启动YouTube则正常。
最新版本的YouTube，去广告功能失效了，后台激活也不会卡死了。
希望去广告新版本能检查一下上述问题，谢谢。

**Comment by fzwzs** [comment]
能否在这里说明支持的版本号，免得过早升级？

**Comment by ohyeah521** [comment]
> 以前版本的YouTube，从后台激活时，有时会造成手机卡死，新启动YouTube则正常。
> 最新版本的YouTube，去广告功能失效了，后台激活也不会卡死了。
> 希望去广告新版本能检查一下上述问题，谢谢。

建议先降级使用，最新版本的广告代码变动较大，原有策略暂时失效。

**Comment by ajmz** [comment]
> > 以前版本的YouTube，从后台激活时，有时会造成手机卡死，新启动YouTube则正常。
> > 最新版本的YouTube，去广告功能失效了，后台激活也不会卡死了。
> > 希望去广告新版本能检查一下上述问题，谢谢。
> 
> 建议先降级使用，最新版本的广告代码变动较大，原有策略暂时失效。

谢谢，已经降级使用。

**Comment by guaxian** [comment]
> 持

能告诉我支持的版本号吗，试了几个都不行

**Comment by ohyeah521** [comment]
> > 持
> 
> 能告诉我支持的版本号吗，试了几个都不行

捐赠用户适配到：15.36.40
