### ISSUE TITLE
这才是最新版本。

### ISSUE THREAD

**Issue by GAY520** [ohyeah521/NoAds-For-YouTube#15]
![Screenshot_20190819-175633_YouTube](https://user-images.githubusercontent.com/54234382/63256742-c82afc80-c2aa-11e9-8667-a5d665301d1c.jpg)

**Comment by GAY520** [comment]
你们有问题群吗

**Comment by ohyeah521** [comment]
@GAY520 捐赠50元以上用户有捐赠用户高级群

**Comment by GAY520** [comment]
在哪里捐款？



---原始邮件---
发件人: "ohyeah521"<notifications@github.com>
发送时间: 2019年8月19日(星期一) 晚上8:04
收件人: "ohyeah521/NoAds-For-YouTube"<NoAds-For-YouTube@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"GAY520"<1500732575@qq.com>;
主题: Re: [ohyeah521/NoAds-For-YouTube] 这才是最新版本。 (#15)



@GAY520 捐赠50元以上用户有捐赠用户高级群

**Comment by ohyeah521** [comment]
@GAY520  https://github.com/ohyeah521/NoAds-For-YouTube  这个页面最下面有微信和支付宝的二维码

**Comment by GAY520** [comment]
Razer_1976219762012





---原始邮件---
发件人: "ohyeah521"<notifications@github.com>
发送时间: 2019年8月20日(星期二) 下午5:27
收件人: "ohyeah521/NoAds-For-YouTube"<NoAds-For-YouTube@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"GAY520"<1500732575@qq.com>;
主题: Re: [ohyeah521/NoAds-For-YouTube] 这才是最新版本。 (#15)



@GAY520  https://github.com/ohyeah521/NoAds-For-YouTube  这个页面最下面有微信和支付宝的二维码
