### ISSUE TITLE
youtube無廣告

### ISSUE THREAD

**Issue by anton86511** [ohyeah521/NoAds-For-YouTube#15]
最新版的youtube beta無法使用，會一直跳出廣告，可以請你更新一下嗎？感謝你的用心，我下載舊版的可以用新版的不行，希望可以改善，謝謝：）

**Comment by ohyeah521** [comment]
建议先降级使用，最新版本的广告代码变动较大，原有策略暂时失效。

**Comment by anton86511** [comment]
辛苦了，希望可以支援到新版的，非常感謝你~

ohyeah521 <notifications@github.com> 於 2020年8月26日 週三 下午2:01 寫道：

**Comment by ohyeah521** [comment]
已经适配最新版本目前仅对捐赠50以上的用户开放。

**Comment by chagangzi** [comment]
之前记得捐助过，今天又捐助了点

**Comment by ohyeah521** [comment]
> 之前记得捐助过，今天又捐助了点

捐助100以上请备注微信，拉你进微信群
