### ISSUE TITLE
提示只有购买特别版用户才可用

### ISSUE THREAD

**Issue by garypang13** [ohyeah521/NoAds-For-YouTube#17]
![Screenshot_20190824-010037_NoAdsBackgroundPlaybackYT](https://user-images.githubusercontent.com/48883331/63609942-ca72bb00-c60a-11e9-86a5-ee0493be9e6a.jpg)这个是说必须捐赠才能使用是吗 目前去广告 锁屏播放都无效

**Comment by ohyeah521** [comment]
不是必须的，免费也可以用，只有部分额外的功能需要收费，以支付服务器费用。

**Comment by jiaying05** [comment]
> 小米9Pro
> 手机系统MIUI12 20.8.13
> youtube版本15.33.34 #15



> 小米9Pro
> 手机系统MIUI12 20.8.13
> youtube版本15.33.34 #15
