### ISSUE TITLE
Ads on 14.33.56

### ISSUE THREAD

**Issue by DanGLES3** [ohyeah521/NoAds-For-YouTube#18]
Looks like Google changed the ad code again

**Comment by ohyeah521** [comment]
Just finished the adaptation of the new version, it should be ready to use.



ohyeah521@gmail.com
 
From: DanGLES3
Date: 2019-08-24 06:30
To: ohyeah521/NoAds-For-YouTube
CC: Subscribed
Subject: [ohyeah521/NoAds-For-YouTube] Ads on 14.33.56 (#18)
Looks like Google changed the ad code again

**Comment by DanGLES3** [comment]
Thanks, I'll be waiting for the updated APK

**Comment by ohyeah521** [comment]
> Thanks, I'll be waiting for the updated APK

do not need updated apk , it's update from cloud. now it's work, u  can have a try.

**Comment by DanGLES3** [comment]
@ohyeah521 I'm still getting ads, even after restarting YouTube

**Comment by ohyeah521** [comment]
> @ohyeah521 I'm still getting ads, even after restarting YouTube

reboot

**Comment by DanGLES3** [comment]
@ohyeah521 seems to be working now, thank you

**Comment by DanGLES3** [comment]
Sorry to bother you but the ads came back ![](https://i.imgur.com/BUAJLRJ.png)

**Comment by DanGLES3** [comment]
Sorry to bother you but the ads are still appearing even after a reboot ![](https://i.imgur.com/t4g7HyQ.png)

**Comment by DanGLES3** [comment]
It seems to be very rare but they still happen

**Comment by ohyeah521** [comment]
> It seems to be very rare but they still happen

i'll test it and find out why

**Comment by ohyeah521** [comment]
@DanGLES3  please update

**Comment by DanGLES3** [comment]
@ohyeah521 thank you very much, now it's working 😁
