### ISSUE TITLE
Disable running in background?

### ISSUE THREAD

**Issue by vertigoelectric** [ohyeah521/NoAds-For-YouTube#19]
I have the NoAdsBackgroundPlaybackYT module and it works great.  However, I only want to remove ads.  I don't want the background playback.  Unfortunately, this seems to be the only app I can find that successfully removes YT ads.  Is there a way to disable the background playback this module provides while still maintaining ad removal?

**Comment by ohyeah521** [comment]
The new version of the advertising code has changed a lot, do not upgrade first, if you only want to go to the advertising function, I can post a separate version later

**Comment by vertigoelectric** [comment]
That would be awesome.  You're the best.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
