### ISSUE TITLE
Unable to install 2.0.7

### ISSUE THREAD

**Issue by blockberd** [ohyeah521/NoAds-For-YouTube#19]
I'm unable to install 2.0.7 on my stock Pixel 3a with Android 9. When installing, it just says "app couldn't be installed". No error code or error message what so ever.

**Comment by underdoq** [comment]
I had previous version installed and i had to uninstall it thru edxposed then reboot, then i installed new version and reboot. I installed susceffuly. Check if you have it installed, also i think you have to root and install xposed

**Comment by blockberd** [comment]
Yes, that worked. Thank you.
