### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by zabhisaeed** [ohyeah521/NoAds-For-YouTube#2]
Can you make debug version?  Please share

**Comment by ohyeah521** [comment]
why u need a debug version ? i do not understand

**Comment by zabhisaeed** [comment]
![Screenshot_2019-05-15-14-11-26](https://user-images.githubusercontent.com/37423156/57763765-89b9fa80-771b-11e9-9d6a-da95aaee3fe7.png)
Because easy to figure out which ads are running

**Comment by ohyeah521** [comment]
My way of advertising is relatively low-level. I reversed the address of the ad created by YouTube and closed it directly, so I didn't access the ad link at all. 
So the debug version can't help you find the ad link.
