### ISSUE TITLE
首页和部分广告无法完全去除

### ISSUE THREAD

**Issue by woeijiunn88** [ohyeah521/NoAds-For-YouTube#2]
如图所示，预览图无法移除，但视频title却能移除。
![Screenshot_20191220-174714.jpg](https://i.loli.net/2019/12/20/peBvy39qolGg6IJ.jpg)

还有一个，下面的广告是否能做到移除呢？
![Screenshot_20191220-175005.jpg](https://i.loli.net/2019/12/20/jXDtRCUxQboz146.jpg)

以上~

**Comment by ohyeah521** [comment]
我这里都可以移除，你用的app是什么版本的，操作系统是什么版本

**Comment by woeijiunn88** [comment]
> 我这里都可以移除，

不懂你是不是没有留意到，
其实在前几个版本就已经有这样的问题..
还是地区问题导致这样（应该不可能

> 你用的app是什么版本的，操作系统是什么版本

安卓9, Pixel Experience, YouTube版本为14.50.53
EdXposed 版本为 90.0-v0.4.5.1_beta(4463) (SandHook)

**Comment by baymax55** [comment]
旧版本YouTube app可以完全移除
