### ISSUE TITLE
后台和锁屏播放功能

### ISSUE THREAD

**Issue by heallly** [ohyeah521/NoAds-For-YouTube#20]
这两个功能是只有捐赠之后才能用吗，目前最新版本无法使用呢

**Comment by ohyeah521** [comment]
后台功能应该是可以使用的，锁屏无法播放，正在调试

**Comment by heallly** [comment]
好的，感谢！
那请问一下后台播放需要在哪开启吗，我这边测试还是不行的

**Comment by ohyeah521** [comment]
@heallly   已经修复14.34.54 版本后台播放问题
