### ISSUE TITLE
催更

### ISSUE THREAD

**Issue by cchhuuaann1** [ohyeah521/NoAds-For-YouTube#26]
看了一下最近YouTube的Google store的评论  你不更插件 我不敢更YouTube....

**Comment by ohyeah521** [comment]
@cchhuuaann1  油管的版本适配是云更新，不用更新插件，插件最新版本2.0.9

**Comment by cchhuuaann1** [comment]
YouTube更新到最新版以后 后台播放/锁屏播放这个功能挂了

**Comment by Joxon** [comment]
目前最新可用版本是14.40.52
https://m.apkpure.com/youtube/com.google.android.youtube/download/1440522000-APK?from=versions%2Fversion

**Comment by ohyeah521** [comment]
@joxon 已经适配了14.40.52

**Comment by ohyeah521** [comment]
@cchhuuaann1  油管版本号，插件版本，操作系统版本请详细提供

**Comment by cchhuuaann1** [comment]
> @cchhuuaann1 油管版本号，插件版本，操作系统版本请详细提供

Google store推送的YouTube版本是14.42.52  插件版本就是2.0.9 手机小米6 系统 MIUI11(Android 9)

**Comment by ohyeah521** [comment]
@cchhuuaann1  请提供一下apk文件吧，我这里目前还没推送

**Comment by cchhuuaann1** [comment]
> @cchhuuaann1 请提供一下apk文件吧，我这里目前还没推送

https://drive.google.com/file/d/11VnJgnwoKe8zEfDUXsrzffXByZsnLNMF/view?usp=drivesdk

**Comment by ohyeah521** [comment]
@cchhuuaann1 已经适配了，完全退出YouTube，然后在启动即可。
