### ISSUE TITLE
Where get latest builds?

### ISSUE THREAD

**Issue by NULL0B** [ohyeah521/NoAds-For-YouTube#27]
Hello i was wondering how to get latest builds? WeChat QQ not available could  you create a Telegram group?

**Comment by ohyeah521** [comment]
https://t.me/joinchat/2UjxUW7dMQ9lNDc1

**Comment by taken7** [comment]
YouTube 16.05.35， Android 8.0， lsp1.02，完美去所有廣告

**Comment by bc352562984** [comment]
> YouTube 16.05.35， Android 8.0， lsp1.02，完美去所有廣告

没有任何作用

**Comment by ohyeah521** [comment]
> > YouTube 16.05.35， Android 8.0， lsp1.02，完美去所有廣告
> 
> 没有任何作用

高版本仅捐赠100元以上的用户进行适配，商店的版本不做最新版本适配
