### ISSUE TITLE
Background play isn't working anymore with the latest version of YouTube 

### ISSUE THREAD

**Issue by tupac55** [ohyeah521/NoAds-For-YouTube#27]
Hi, I've the 2.0.9 version of the module installed and the latest version of YouTube (14.42. 52) also installed, I don't have ads but background play isn't working..

**Comment by ohyeah521** [comment]
@tupac55  i'll upgrade it tonight, please  try it latter.

**Comment by ohyeah521** [comment]
@tupac55  can you tell me where can i get YOUTUBE 14.42. 52,  i can not find it.

**Comment by tupac55** [comment]
@ohyeah521

https://www.apkmirror.com/apk/google-inc/youtube/youtube-14-42-52-release/

Heres the apk :) thanks for looking at it

**Comment by ohyeah521** [comment]
@tupac55  done, allready work. try again.

**Comment by tupac55** [comment]
There's no update on xposed repo how do I try again? Just open your app then reboot?

**Comment by tupac55** [comment]
@ohyeah521 , tried opening your app then clicking Create then reboot still not working :( and i'm using the latest version of the repo 2.0.9

**Comment by ohyeah521** [comment]
@tupac55   apkmirror only had api level 19 , may be you version is api 21, there are two version, one suit for android 4.4 latter,the other one is for android 5.0 latter

**Comment by ohyeah521** [comment]
@tupac55  copy youtube apk from you phone ,and send  it to me.

**Comment by tupac55** [comment]
https://drive.google.com/open?id=10QYk7GWMGqb372kLPmCXwiDI7i4mpc0m

Here's my apk from "Data/App/"

**Comment by ohyeah521** [comment]
@tupac55  I've adapted this version of yours, just stop youtube  and restart it.

**Comment by ohyeah521** [comment]
@tupac55   uninstall  youtube and  download from playstore again,may be will work again.

**Comment by tupac55** [comment]
@ohyeah521  Thanks , it works well now :D !

**Comment by underdoq** [comment]
@ohyeah521 Thanks works for me too.

Would you advise, that we should wait few days or weeks before installing latest youtube update ?

**Comment by ohyeah521** [comment]
@underdoq Yes, I recommend waiting at least 1 week after the upgrade, because different countries push different versions, I can not get the latest version in time, so there is no way to update
