### ISSUE TITLE
Background playback not working

### ISSUE THREAD

**Issue by lukish04** [ohyeah521/NoAds-For-YouTube#29]
Hi
I have installed your module. Its removing adds from Youtube, but background playback is not working.
My phone is OnePlus 3T, Android 9, OxygenOS 9.0.6.
YouTube app version 16.08.35.

**Comment by ohyeah521** [comment]
Support all versions below YouTube v16.07.38

**Comment by lukish04** [comment]
Yes, with older version it works. Thx
