### ISSUE TITLE
Donate and Then… ???

### ISSUE THREAD

**Issue by GiantWaffle** [ohyeah521/NoAds-For-YouTube#3]
Hello,

This isn't an issue.  It's just a question.  I didn't see an email address, so I had to ask it here.  Sorry.

If I Donate using PayPal, how will the app know that I have paid, the next time I need to install it?

I ask, because I didn't see anywhere in the app where the user "signs in" or anything, for identification purposes.

Does the Donation add any functions to the app?  Or is the app already fully functional and the Donation is simply and only done as a thank you?

I am not complaining.  I've donated with that understanding on many, many occasions.  I do believe in supporting the work of developers whose apps I am benefitting from and getting enjoyment from.

I'm only seeking understanding, so that I proceed properly, if it does add some function(s) to the app and so I make sure that I record the proper information, if in fact it will be needed the next time I need to install the app, that's all.

I Thank You Sincerely for Your Time,

Zeuszoos

**Comment by ohyeah521** [comment]
1. This is a free app and it will always be free.

2. All the features of this software are free, donation does not add any features. 
You can uninstall it at any time, install it, and use its full functionality.

3. Donation is only to thank me for the time and effort. In order to protect my privacy, I will not announce the name of the donor, but I will thank you in my heart.

**Comment by GiantWaffle** [comment]
Thank you for your quick and helpful response.  I appreciate it.

Just a few humble suggestions, please?

1) Just to be helpful and not to be rude in any way, I would like to humbly offer a couple of corrections in the line of text that appears in the app when it's opened.

When opening your app after a properly performed install, it shows the following text near the bottom;

"NoAds For YouTube already actived"

Just FYI, there is no word "actived".  It can be just "active" or "activated".

2) Since the app has a white background, I would humbly suggest making the text Black instead of Neon Green.  Neon is not good for reading on a light background.  While it can look great on a dark background, it tends to wash out on a light background.

3) Could you please make the text a little larger?  Maybe I'm just getting old, but even with my glasses on, it's not easy to read.  Of course, half of that is probably due to the neon effect.

Thank You for Your Time

**Comment by ohyeah521** [comment]
Ok, I will adjust it in the next version.

**Comment by GiantWaffle** [comment]
Thank you.
