### ISSUE TITLE
BackgroundPlayback  - Youtube v16.17.36

### ISSUE THREAD

**Issue by 0username00** [ohyeah521/NoAds-For-YouTube#33]
Hello, the current version of your xposed module, based on YouTubeBackgroundPlayback, does not support Youtube v16.17.36.
Can you please port the recent update of YouTubeBackgroundPlayback to your Xposed module?
Thanks

**Comment by ohyeah521** [comment]
My module supports this function. In order to maintain this project, only users who donate more than 20$ will be updated as soon as possible.
