### ISSUE TITLE
锁屏播放用不了

### ISSUE THREAD

**Issue by huangyong123654** [ohyeah521/NoAds-For-YouTube#35]
youtube  16.20.35   手机1加6T   安卓10

**Comment by ohyeah521** [comment]
捐赠100以上用户才能支持最新版本，如果捐赠请联系我，否则请退回老版本

**Comment by zc998800** [comment]
老版本是到哪个版本呢

**Comment by zc998800** [comment]
服了，下了个老版本14.43.35也没用，都是一年前的版本了，没一个能用的

**Comment by SanbornWen** [comment]
请问4.5.0版本模块支持的最高版本Youtube是多少？
