### ISSUE TITLE
油管不好用

### ISSUE THREAD

**Issue by ScarletDor** [ohyeah521/NoAds-For-YouTube#36]
老哥不好用啊，油管的16.12.32版本，帮忙看一下，所有的广告都在，一个也没有被删掉qaq，手机是红米k20p miui12，安卓10

**Comment by ScarletDor** [comment]
油管14.43.55也不能用

**Comment by ScarletDor** [comment]
突然好用了，感谢大佬

**Comment by ohyeah521** [comment]
新版本仅对捐助100元以上用户开放，请捐助后留下微信或者是给我发邮件。

**Comment by ScarletDor** [comment]
？？？你是说14是新版本？有问题就说有问题
