### ISSUE TITLE
值得购买吗？

### ISSUE THREAD

**Issue by Git-Psyduck** [ohyeah521/NoAds-For-YouTube#44]
我支持软件付费，但是一个去广告要捐赠100元才能用是不是太贵了呢？我用过很多好的软件，也入正过，但我还是不能理解，在lsp仓库里发现了这个模块，装了之后没效果，才发现要进微信群才能用新版本。算了算了，哪里来的回哪里去吧

**Comment by ohyeah521** [comment]
商店的不支持最新版本，请回退老版本即可正常使用。
