### ISSUE TITLE
Hooks could not be applied

### ISSUE THREAD

**Issue by 1alessandro1** [ohyeah521/NoAds-For-YouTube#49]
- phone model: Xiaomi mi A1 (tissot)
- system version: crdroid 7.15 (A11)
- YouTube version: 17.09.33
- com.wovow.youtubehelper version: 4.5.0

I've installed the module and rebooted the device but it did not ask for storage permission, so I couldn't enable it even if I would (in settings it says `sensors` is the only requested/allowable)
However in conclusion the lsposed module does not seem to hook anything hence YouTube app has stock ads behaviour

Error log: 
[LSPosed_2022-03-19T04_47_21.545.zip](https://github.com/ohyeah521/NoAds-For-YouTube/files/8308537/LSPosed_2022-03-19T04_47_21.545.zip)

**Comment by 1alessandro1** [comment]
Please let me know which build of YouTube is known to be working, e.g (1527248320)

**Comment by 1alessandro1** [comment]
I've also tried 16.47.35 build com.google.android.youtube 1524751808 build 

For me it has problems with `Failed to connect 127.0.0.1:80`
It says "No hook details were found for the version of YouTube 16.46.35..."

**Comment by ohyeah521** [comment]
Version 8.0.0 has been released on the store.
Supporting YouTube version 17.14.35 to advertise and play in the background;
Support YouTube Music 5.02.50 version to advertise, background playback;
Supports all versions of Twitter to go to advertising
