### ISSUE TITLE
2.0.1 Crash YouTube Mi9

### ISSUE THREAD

**Issue by rogodra** [ohyeah521/NoAds-For-YouTube#5]
2.0.1 Crash YouTube on Xiaomi Mi 9. MIUI 10 and Android 9. Version 2.0.0 correctly. Thanks!

**Comment by ohyeah521** [comment]
Please upload the crash log so that I can locate the bug. Is it always crashing?

**Comment by ohyeah521** [comment]
@rogodra Please download the new version and fix the bug.

**Comment by rogodra** [comment]
Work! Thanks
