### ISSUE TITLE
Shorts bug

### ISSUE THREAD

**Issue by reimu-electric** [ohyeah521/NoAds-For-YouTube#56]
Mobile phone model number:M2011K2C(Xiaomi Mi11)
Android Version:11  YouTube Version:17.14.35

I am using this environment and there is a bug that prevents the comments box to the right of YouTube Shorts from showing up. Please let me know the cause.

![IMG_20220421_215823](https://user-images.githubusercontent.com/99260247/164463261-ee4e630a-f8ee-4fcc-886e-5200a0fcd74e.jpg)

**Comment by ohyeah521** [comment]
I don't know what's the reason
