### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by TeaqariaWTF** [ohyeah521/NoAds-For-YouTube#58]
Poco X3 Android 12.1
YouTube 7.15.33 

I'm using it for the first time, I wonder if it's normal for these ads to still appear
![Screenshot_20220422-010839_YouTube](https://user-images.githubusercontent.com/90970076/164560022-4b2e08ac-09e6-4cdd-9ef5-cb7bd658de02.png)

**Comment by ohyeah521** [comment]
Go back to the previous version. This version is not supported
