### ISSUE TITLE
Background Playback not working

### ISSUE THREAD

**Issue by Dark-Cod3r** [ohyeah521/NoAds-For-YouTube#6]
Hi.
After recent YouTube update.. background playback and PiP not working any more.. any fix for that.?!
Thanks

**Comment by ohyeah521** [comment]
now ,it's support YT 15.09.36

**Comment by infoflo7** [comment]
Hi ohyeah521. Sadly latest Youtube 15.12.33 breaks background playback.

**Comment by Dark-Cod3r** [comment]
Hi. Background playback not working anymore again with latest YT update..any fix..?!

**Comment by ohyeah521** [comment]
> Hi. Background playback not working anymore again with latest YT update..any fix..?!

now,it's support  15.12.33 version

**Comment by infoflo7** [comment]
Hi ohyeah521, background playback does not work anymore in latest youtube (15.13.33). Can you fix it?

**Comment by ohyeah521** [comment]
> Hi ohyeah521, background playback does not work anymore in latest youtube (15.13.33). Can you fix it?

in my county,i can not get the laster version from googleplay, please wait ,

**Comment by infoflo7** [comment]
I see it is fixed now, thank you :)
