### ISSUE TITLE
Ads on the home.

### ISSUE THREAD

**Issue by Crescendo-BLYAT** [ohyeah521/NoAds-For-YouTube#6]
Bro, there's still an ads on the top of the home in portrait orientation.
It's gone on landscape.

The rest is clean.

**Comment by ohyeah521** [comment]
That's the only very simple video ad that hasn't been removed, it doesn't affect the user experience, so I didn't plan to remove it or it would add some extra work to me.

**Comment by Crescendo-BLYAT** [comment]
strangely its not there when switched to landscape mode....

**Comment by ohyeah521** [comment]
This should be the strategy of its advertising video display, because when the horizontal screen, the vertical space is limited, if the display advertising, the user experience is not good
