### ISSUE TITLE
LSPosed details

### ISSUE THREAD

**Issue by gjf** [ohyeah521/NoAds-For-YouTube#61]
It would be very useful to provide additional information regarding installation of this module in LSPosed.
What should be enabled? System framework? Youtube / YT Music / Twitter? Or LSPosed is not supported at all?
![Screenshot_20220525-173219](https://user-images.githubusercontent.com/322186/170297763-e991c807-44b2-4bc5-be3c-87bea1be9b6e.jpg)

**Comment by Yzzzi** [comment]
Trying to make it work with LSPosed too, but no luck.
Magisk 24.3
LSPosed
```
API version
93

Injection Interface
Zygisk

Dex Optimizer Wrapper
Supported

Framework version
1.8.3 (6552)

Manager version
1.8.3 (6552)

System version
11 (API 30)

Device
Xiaomi POCO M2007J20CG 

System ABI
arm64-v8a
```

**Comment by ohyeah521** [comment]
Support YouTube version 17.14.35 to advertise and play in the background
Support YouTube music version 5.02.50 to advertise and play in the background
Support all versions of Twitter to advertise

do not upgrade new version

**Comment by EkriirkE** [comment]
> Support YouTube version 17.14.35 to advertise and play in the background Support YouTube music version 5.02.50 to advertise and play in the background Support all versions of Twitter to advertise
> 
> do not upgrade new version

Ok, sure.  But the question is are those the correct apps needed in LSposed for this to work

**Comment by ohyeah521** [comment]
https://github.com/Xposed-Modules-Repo/com.wovow.youtubehelper

**Comment by gjf** [comment]
> > Support YouTube version 17.14.35 to advertise and play in the background Support YouTube music version 5.02.50 to advertise and play in the background Support all versions of Twitter to advertise
> > 
> > do not upgrade new version
> 
> Ok, sure.  But the question is are those the correct apps needed in LSposed for this to work

Looks like the dev doesn't understand us.
But I don't know Chinese unfortunately...

**Comment by ohyeah521** [comment]
Only these 3 items need to be enabled, otherwise the lsposed hook will not take effect

![微信截图_20220527173952](https://user-images.githubusercontent.com/1449374/170674439-16ab2ca4-e881-4e4c-8bdd-d2b48546cf2e.png)
