### ISSUE TITLE
Icon not hiding

### ISSUE THREAD

**Issue by MuhammadBayiz** [ohyeah521/NoAds-For-YouTube#63]
I Have Enabled Hiding Icon Option But The Icon Is Still Visible And When I Press It It Takes Me To The "App Settings".

**Comment by ohyeah521** [comment]
After the Android system 10.0, there are strict restrictions on the hidden icons of applications. The Android official website means that unless it is a system application or an app that does not contain the four major components of Android and does not apply for any permissions, the icon can be hidden.
