### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by Chastinian** [ohyeah521/NoAds-For-YouTube#64]
手机型号：Redmi K30 5G
安卓版本：12（SDK Version：32）
YouTube 版本：17.24.34(1529992640)
YouTube Music 版本：5.12.51(51251240)
Bug描述：模块任何功能开启后皆毫无作用。
日志：稍后即将提供

**Comment by Chastinian** [comment]
日志下载地址：https://chastinian.lanzouw.com/iUxCF07co1te

**Comment by ohyeah521** [comment]
不是bug，你的版本太新，解决办法：
1、降级到老版本
      支持YouTube 17.14.35版本去广告，后台播放
      支持YouTube Music 5.02.50 版本本去广告，后台播放
      支持Twitter所有版本去广告
2、成为捐赠用户，捐赠100以上的网友会第一时间在微信群内获取到最新版本的破解进度信息

**Comment by samcbc** [comment]
https://fs17.apkbog.com/storage/5/715/3715/arm64_v8a-armeabi_v7a-x86-x86_64/YouTube-17.14.35.apk?s=Efd4U__hntw0T4ho7g4Hsg&e=1660045505&lang=en&apk_id=1608
17.14.35下载
