### ISSUE TITLE
youtube 15.15.38

### ISSUE THREAD

**Issue by Termicj** [ohyeah521/NoAds-For-YouTube#8]
Yesterday, YouTube was updated and background playback disappeared. Roll back to previous version and background playback is again available

**Comment by Mike-Ferretti** [comment]
I'm having the same exact problem. Ads are now playing on the new app as well.

**Comment by Termicj** [comment]
Then we will wait for clarity from a respected developer.

**Comment by ohyeah521** [comment]
Because the time of Google's upgrade is different for different countries and regions, I can't get the latest version in the first time, so there will be a delay in the update. Therefore, please do not update to the latest version as soon as possible.


Just adapted to 15.15.38
